name: router_core
description: Core routing infrastructure for dental ecosystem apps
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
