name: growth_flutter_fase_05_riverpood
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  app_ui_kit:
    git:
      url: https://github.com/abialex/growth_flutter_fase_04_riverpood.git
      ref: v0.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_riverpod: ">=3.3.2 <3.4.0"
  meta: ^1.16.0
  router_core:
    path: ../../packages/router_core
  supabase_flutter: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
